import Foundation
import Testing

/// `test-vectors/reactions.json`, decoded once for every reaction vector suite. The canonical copy
/// lives in the orchestrator repo and is generated by `gen_reactions.py`; this one is synced. A
/// failure in any suite reading it is either a real regression or a deliberate cross-platform
/// decision that has to be made in the generator and re-synced to both platforms — never a local
/// edit.
struct ReactionFixture: Decodable {

    struct MergeVector: Decodable {
        struct Expect: Decodable {
            let pills: [Pill]
            let calls: [Call]
            let errors: [String]
        }
        let name: String
        let selfID: String
        let steps: [Step]
        let expect: Expect
        let note: String

        private enum CodingKeys: String, CodingKey {
            case name, steps, expect, note
            case selfID = "self"
        }
    }

    struct Pill: Decodable, Equatable, CustomStringConvertible {
        let emoji: String
        let count: UInt64
        let selfReacted: Bool
        let pending: Bool

        var description: String { "\(emoji)×\(count)\(selfReacted ? " self" : "")\(pending ? " pending" : "")" }
    }

    struct Call: Decodable, Equatable, CustomStringConvertible {
        let op: String
        let emoji: String

        var description: String { "\(op) \(emoji)" }
    }

    /// A summary entry, or a successful response's reaction, which has no `emoji`.
    struct Reaction: Decodable {
        let emoji: String?
        let count: UInt64
        let isSelf: Bool
        let version: UInt64

        private enum CodingKeys: String, CodingKey {
            case emoji, count, version
            case isSelf = "self"
        }
    }

    enum Step: Decodable {
        case summary([Reaction])
        case update(emoji: String, actor: String, action: String, count: UInt64, version: UInt64)
        case tap(emoji: String)
        case respond(emoji: String, result: String, reaction: Reaction?)

        private enum CodingKeys: String, CodingKey {
            case op, reactions, emoji, actor, action, count, version, result, reaction
        }

        init(from decoder: Decoder) throws {
            let c = try decoder.container(keyedBy: CodingKeys.self)
            let op = try c.decode(String.self, forKey: .op)
            switch op {
            case "summary":
                self = .summary(try c.decode([Reaction].self, forKey: .reactions))
            case "update":
                self = .update(
                    emoji: try c.decode(String.self, forKey: .emoji),
                    actor: try c.decode(String.self, forKey: .actor),
                    action: try c.decode(String.self, forKey: .action),
                    count: try c.decode(UInt64.self, forKey: .count),
                    version: try c.decode(UInt64.self, forKey: .version)
                )
            case "tap":
                self = .tap(emoji: try c.decode(String.self, forKey: .emoji))
            case "respond":
                self = .respond(
                    emoji: try c.decode(String.self, forKey: .emoji),
                    result: try c.decode(String.self, forKey: .result),
                    reaction: try c.decodeIfPresent(Reaction.self, forKey: .reaction)
                )
            default:
                throw DecodingError.dataCorruptedError(forKey: .op, in: c, debugDescription: "unknown op \(op)")
            }
        }
    }

    struct OrderVector: Decodable {
        struct Pill: Decodable {
            let emoji: String
            let count: UInt64
            let boostTotal: UInt64
        }
        let name: String
        let pills: [Pill]
        let expect: [String]
        let note: String
    }

    struct StripVector: Decodable {
        struct SelfReaction: Decodable {
            let emoji: String
            let reactedAt: Double
        }
        struct Entry: Decodable, Equatable {
            let emoji: String
            let highlighted: Bool
        }
        let name: String
        let recents: [String]
        let selfReactions: [SelfReaction]
        let expect: [Entry]
        let note: String
    }

    struct RecentsVector: Decodable {
        struct Use: Decodable {
            let emoji: String
            let usedAt: Double
        }
        let name: String
        let uses: [Use]
        let undrawable: [String]
        let limit: Int
        let expect: [String]
        let note: String
    }

    struct DrawabilityVector: Decodable {
        let emoji: String
        let drawable: Bool
        let note: String
    }

    let defaults: [String]
    let merge: [MergeVector]
    let order: [OrderVector]
    let strip: [StripVector]
    let recents: [RecentsVector]
    let drawability: [DrawabilityVector]
}

func loadReactionFixture() throws -> ReactionFixture {
    let url = try #require(
        Bundle.module.url(forResource: "reactions", withExtension: "json", subdirectory: "Fixtures")
    )
    return try JSONDecoder().decode(ReactionFixture.self, from: Data(contentsOf: url))
}
