syntax = "proto3";

package flipcash.intent.v1;

option go_package = "github.com/code-payments/flipcash2-protobuf-api/generated/go/intent/v1;intentpb";
option java_package = "com.codeinc.flipcash.gen.intent.v1";
option objc_class_prefix = "FPBIntentV1";

import "common/v1/common.proto";
import "validate/validate.proto";

message AppMetadata {
    oneof domain {
        option (validate.required) = true;

        ChatMetadata chat = 1;
    }
}

// Additional metadata provided to SubmitIntent when doing payments in a chat
message ChatMetadata {
    common.v1.ChatId chat_id = 1 [(validate.rules).message.required = true];

    oneof type {
        option (validate.required) = true;

        ContactDmPayment contact_dm_payment = 2;
        TipDmPayment     tip_dm_payment     = 3;
    }

    // For sending a payment to a contact in a DM
    message ContactDmPayment {
        // Source phone number that is paying. This is validated to be linked to the sender.
        common.v1.PhoneNumber source = 1 [(validate.rules).message.required = true];

        // Destination phone number that is being paid. This is validated to be linked to the receiver.
        common.v1.PhoneNumber destination = 2 [(validate.rules).message.required = true];
    }

    // For sending a DM payment to someone using their user ID, which maps
    // directly to/from a public key.
    message TipDmPayment {
        // Location in the app the payment was sent from
        enum Location {
            TIPCARD = 0;
            CHAT    = 1;
        }
        Location location = 1;
    }
}
