#!/usr/bin/env bash

set -e

DESTINATION_FILE="$1"
PREFIX="$2"

if [ -z "${DESTINATION_FILE}" ]
then
  echo "error: Failed to build Google credentials plist. No destination file path provided."
  exit 1
fi

if [ -z "${PREFIX}" ]
then
  echo "Using default prefix: G_"
  PREFIX="G_"
else
  echo "Using prefix: $PREFIX"
fi

PLIST_CONTENT=""

start_plist() {
    PLIST_CONTENT+="<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
"
}

end_plist() {
    PLIST_CONTENT+="</dict>
</plist>"
}

validate() {
    ENV_KEY="${PREFIX}$1"
    if [ -z "${!ENV_KEY}" ]; then
      echo "error: Failed to build Google credentials plist. No environment value set for key: $ENV_KEY"
      exit 1
    fi
}

string() {
    KEY=$1
    ENV_KEY="${PREFIX}$1"
    validate $1
    VALUE="${!ENV_KEY:-default_value}"
    PLIST_CONTENT+="	<key>$KEY</key>
	<string>$VALUE</string>
"
}

boolean() {
    KEY=$1
    ENV_KEY="${PREFIX}$1"
    validate $1
    BOOL="${!ENV_KEY}"
    if [ "$BOOL" = "YES" ]; then
      VALUE=true
    else
      VALUE=false
    fi
    PLIST_CONTENT+="	<key>$KEY</key>
	<$VALUE/>
"
}

start_plist

# string CLIENT_ID
# string REVERSED_CLIENT_ID
string API_KEY
string GCM_SENDER_ID
string PLIST_VERSION
string BUNDLE_ID
string PROJECT_ID
string STORAGE_BUCKET

boolean IS_ADS_ENABLED
boolean IS_ANALYTICS_ENABLED
boolean IS_APPINVITE_ENABLED
boolean IS_GCM_ENABLED
boolean IS_SIGNIN_ENABLED
boolean FirebaseAppDelegateProxyEnabled
boolean GoogleUtilitiesAppDelegateProxyEnabled
string GOOGLE_APP_ID

end_plist
echo "$PLIST_CONTENT" > "${DESTINATION_FILE}"
echo "warning: Generated a new Google plist."
