#!/usr/bin/env bash

## 1. Exit if any command fails
## ----------------------------

set -e

## 2. Check params
## ---------------

SOURCE_ROOT="$1"
PREFIX="$2"

if [ ! -d "$SOURCE_ROOT" ]
then
  echo "error: No source directory provided: $SOURCE_ROOT"
  exit
fi

echo "Source directory: $SOURCE_ROOT"

# Don't run this on GitHub, there's no point
if [ "$GITHUB_ACTIONS" = "true" ]; then
  exit 0
fi

cd "$SOURCE_ROOT/Configurations"

if [ ! -f "secrets.local.xcconfig" ]; then
  cd "$SOURCE_ROOT/Scripts"
  echo "warning: No secrets found. Pulling credentials repo..."
  ./pull_secrets "$SOURCE_ROOT" "$PREFIX"
fi
