#!/usr/bin/env bash

APP=""

while getopts s:a: flag
do
    case "${flag}" in
        s) SKIP_PULL=1;;
        a) APP=${OPTARG};;
    esac
done

# Set directories based on app
if [[ "$APP" == "flipchat" ]]; then
    PROTOS_ROOT_DIR="../FlipchatAPI/Sources/FlipchatAPI"
    PROTOS_DIR="../FlipchatAPI/Sources/FlipchatAPI/proto"
    DEPS_DIR="../FlipchatAPI/Sources/FlipchatAPI/proto_deps"
    GENERATED_DIR="../FlipchatAPI/Sources/FlipchatAPI/Generated"
    PULL_REPO="code-payments/flipchat-protobuf-api"
    PULL_BRANCH="main"
    PREFIX=""

elif [[ "$APP" == "flipchatPayments" ]]; then
    PROTOS_ROOT_DIR="../FlipchatPaymentsAPI/Sources/FlipchatPaymentsAPI"
    PROTOS_DIR="../FlipchatPaymentsAPI/Sources/FlipchatPaymentsAPI/proto"
    DEPS_DIR="../FlipchatPaymentsAPI/Sources/FlipchatPaymentsAPI/proto_deps"
    GENERATED_DIR="../FlipchatPaymentsAPI/Sources/FlipchatPaymentsAPI/Generated"
    PULL_REPO="code-payments/code-protobuf-api"
    PULL_BRANCH="fc"
    PREFIX=""

elif [[ "$APP" == "flipcashCore" ]]; then
    PROTOS_ROOT_DIR="../FlipcashCoreAPI/Sources/FlipcashCoreAPI"
    PROTOS_DIR="../FlipcashCoreAPI/Sources/FlipcashCoreAPI/proto"
    DEPS_DIR="../FlipcashCoreAPI/Sources/FlipcashCoreAPI/proto_deps"
    GENERATED_DIR="../FlipcashCoreAPI/Sources/FlipcashCoreAPI/Generated"
    PULL_REPO="code-payments/flipcash-protobuf-api"
    PULL_BRANCH="main"
    PREFIX=""

elif [[ "$APP" == "flipcashPayments" ]]; then
    PROTOS_ROOT_DIR="../FlipcashAPI/Sources/FlipcashAPI"
    PROTOS_DIR="../FlipcashAPI/Sources/FlipcashAPI/proto"
    DEPS_DIR="../FlipcashAPI/Sources/FlipcashAPI/proto_deps"
    GENERATED_DIR="../FlipcashAPI/Sources/FlipcashAPI/Generated"
    PULL_REPO="code-payments/ocp-protobuf-api"
    PULL_BRANCH="main"
    PREFIX=""
    
elif [[ "$APP" == "code" ]]; then
    PROTOS_ROOT_DIR="../CodeAPI/Sources/CodeAPI"
    PROTOS_DIR="../CodeAPI/Sources/CodeAPI/proto"
    DEPS_DIR="../CodeAPI/Sources/CodeAPI/proto_deps"
    GENERATED_DIR="../CodeAPI/Sources/CodeAPI/Generated"
    PULL_REPO="code-payments/code-protobuf-api"
    PULL_BRANCH="main"
    PREFIX=""
    
else
    echo "error: Unknown app type '$APP'. Use 'code' or 'flipchat'."
    exit 1
fi

# Skip pull logic if needed
if [[ SKIP_PULL -eq 0 ]];
then
    # Pull protos
    rm -rf $PROTOS_DIR
    ./pull_protos  $PULL_REPO  $PULL_BRANCH  $PROTOS_ROOT_DIR

    # Copy over proto dependencies
    cp -a "$DEPS_DIR/." $PROTOS_DIR
else
    echo "warning: Skipping proto update from repo, just running code generator."
fi

# Generate Swift models
rm -rf $GENERATED_DIR
mkdir -p $GENERATED_DIR

./generate $PROTOS_DIR $GENERATED_DIR $PREFIX
