name: Test

on: push

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@master

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Use Xcode 15
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Setup simulator
        id: version
        run: |
          CURRENT_SIMULATOR_UUID=$(xcrun simctl create TestDevice com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-17-0)
          echo "CURRENT_SIMULATOR_UUID=$CURRENT_SIMULATOR_UUID" >> $GITHUB_ENV
          
      - name: Test Code
        run: ./Scripts/test
